export type ProductCategory='pulses'|'beans'
export type ProductStatus='available'|'coming-soon'
export type Product={id:string;sku:string;sortOrder:number;featured:boolean;slug:string;nameEnglish:string;nameNepali:string;category:ProductCategory;packSizes:string[];accentColor:string;accentSoft:string;descriptionEnglish:string;descriptionNepali:string;image?:string;storageEnglish:string;storageNepali:string;useEnglish:string;useNepali:string;status:ProductStatus}
const dryEn='Keep sealed in a cool, dry place away from moisture and direct sunlight.'
const dryNe='चिस्यान र प्रत्यक्ष घामबाट टाढा चिसो, सुख्खा ठाउँमा बन्द गरेर राख्नुहोस्।'
export const products:Product[]=[
{id:'masoor',sku:'SAANJH-MASOOR-1KG',sortOrder:10,featured:true,slug:'masoor-dal',nameEnglish:'Masoor Dal',nameNepali:'मसुरो दाल',category:'pulses',packSizes:['1 kg'],accentColor:'#e04f43',accentSoft:'#fae0da',descriptionEnglish:'An everyday red lentil, carefully packed for simple home cooking.',descriptionNepali:'दैनिक घरायसी खानाका लागि सावधानीपूर्वक प्याक गरिएको मसुरो दाल।',image:'/images/products/masoor-dal.png',storageEnglish:dryEn,storageNepali:dryNe,useEnglish:'Suitable for everyday dal, soups and familiar home-style recipes.',useNepali:'दैनिक दाल, सुप र घरायसी परिकारका लागि उपयुक्त।',status:'available'},
{id:'moong',sku:'SAANJH-MOONG-1KG',sortOrder:20,featured:true,slug:'moong-dal',nameEnglish:'Moong Dal',nameNepali:'मुग दाल',category:'pulses',packSizes:['1 kg'],accentColor:'#397b2b',accentSoft:'#e5f0dc',descriptionEnglish:'Split moong dal packed for dependable everyday meals.',descriptionNepali:'दैनिक भरपर्दो खानाका लागि प्याक गरिएको मुग दाल।',image:'/images/products/moong-dal.png',storageEnglish:dryEn,storageNepali:dryNe,useEnglish:'Use in dal, khichdi and other everyday dishes.',useNepali:'दाल, खिचडी र अन्य दैनिक परिकारमा प्रयोग गर्न सकिन्छ।',status:'available'},
{id:'chana',sku:'SAANJH-CHANA-DAL-1KG',sortOrder:30,featured:true,slug:'chana-dal',nameEnglish:'Chana Dal',nameNepali:'चना दाल',category:'pulses',packSizes:['1 kg'],accentColor:'#e4a41c',accentSoft:'#faedc3',descriptionEnglish:'Split chana dal for familiar, satisfying household recipes.',descriptionNepali:'परिचित र स्वादिला घरायसी परिकारका लागि चना दाल।',image:'/images/products/chana-dal.png',storageEnglish:dryEn,storageNepali:dryNe,useEnglish:'Suitable for dal, curries and traditional preparations.',useNepali:'दाल, तरकारी र परम्परागत परिकारका लागि उपयुक्त।',status:'available'},
{id:'rahar',sku:'SAANJH-RAHAR-1KG',sortOrder:40,featured:true,slug:'rahar-dal',nameEnglish:'Rahar Dal',nameNepali:'रहर दाल',category:'pulses',packSizes:['1 kg'],accentColor:'#e9ad27',accentSoft:'#fff0bd',descriptionEnglish:'A household staple packed for dependable daily cooking.',descriptionNepali:'दैनिक भरपर्दो खानाका लागि प्याक गरिएको घरायसी खाद्यान्न।',image:'/images/products/rahar-dal.png',storageEnglish:dryEn,storageNepali:dryNe,useEnglish:'Cook as a comforting everyday dal with your preferred seasoning.',useNepali:'आफ्नो मनपर्ने झानोसँग दैनिक दालका रूपमा पकाउनुहोस्।',status:'available'},
{id:'maas',sku:'SAANJH-MAAS-1KG',sortOrder:50,featured:false,slug:'maas-dal',nameEnglish:'Maas Dal',nameNepali:'मास दाल',category:'pulses',packSizes:['1 kg'],accentColor:'#594078',accentSoft:'#e8e0f2',descriptionEnglish:'Maas dal for traditional and everyday Nepali cooking.',descriptionNepali:'परम्परागत तथा दैनिक नेपाली खानाका लागि मास दाल।',storageEnglish:dryEn,storageNepali:dryNe,useEnglish:'Use in traditional dal and home-style recipes.',useNepali:'परम्परागत दाल र घरायसी परिकारमा प्रयोग गर्न सकिन्छ।',status:'available'},
{id:'whole-chana',sku:'SAANJH-WHOLE-CHANA-1KG',sortOrder:60,featured:true,slug:'whole-chana',nameEnglish:'Whole Chana',nameNepali:'कालो चना',category:'beans',packSizes:['1 kg'],accentColor:'#86502e',accentSoft:'#eadbce',descriptionEnglish:'Whole brown chickpeas packed for curries, snacks and household meals.',descriptionNepali:'तरकारी, खाजा र घरायसी खानाका लागि प्याक गरिएको कालो चना।',image:'/images/products/whole-chana.png',storageEnglish:dryEn,storageNepali:dryNe,useEnglish:'Suitable for curries, salads, snacks and traditional dishes.',useNepali:'तरकारी, सलाद, खाजा र परम्परागत परिकारका लागि उपयुक्त।',status:'available'},
{id:'bodi',sku:'SAANJH-BODI-1KG',sortOrder:70,featured:false,slug:'bodi',nameEnglish:'Bodi',nameNepali:'बोडी',category:'beans',packSizes:['1 kg'],accentColor:'#dc7a36',accentSoft:'#f7dfcf',descriptionEnglish:'Everyday bodi packed for simple household cooking.',descriptionNepali:'सरल घरायसी खानाका लागि प्याक गरिएको बोडी।',storageEnglish:dryEn,storageNepali:dryNe,useEnglish:'Use in curries, soups and mixed bean dishes.',useNepali:'तरकारी, सुप र मिश्रित गेडागुडीका परिकारमा प्रयोग गर्नुहोस्।',status:'available'},
{id:'seto-kerau',sku:'SAANJH-SETO-KERAU-1KG',sortOrder:80,featured:false,slug:'seto-kerau',nameEnglish:'Seto Kerau',nameNepali:'सेतो केराउ',category:'beans',packSizes:['1 kg'],accentColor:'#7ea54b',accentSoft:'#e7efd8',descriptionEnglish:'White peas for familiar snacks, curries and home recipes.',descriptionNepali:'परिचित खाजा, तरकारी र घरायसी परिकारका लागि सेतो केराउ।',storageEnglish:dryEn,storageNepali:dryNe,useEnglish:'Soak as needed and use in snacks, curries or soups.',useNepali:'आवश्यकता अनुसार भिजाएर खाजा, तरकारी वा सुपमा प्रयोग गर्नुहोस्।',status:'available'},
{id:'kabuli',sku:'SAANJH-KABULI-CHANA-1KG',sortOrder:90,featured:false,slug:'kabuli-chana',nameEnglish:'Kabuli Chana',nameNepali:'काबुली चना',category:'beans',packSizes:['1 kg'],accentColor:'#b59b72',accentSoft:'#eee7dc',descriptionEnglish:'Kabuli chickpeas for curries, chaat and everyday dishes.',descriptionNepali:'तरकारी, चाट र दैनिक परिकारका लागि काबुली चना।',storageEnglish:dryEn,storageNepali:dryNe,useEnglish:'Suitable for curries, chaat, hummus and salads.',useNepali:'तरकारी, चाट, हुमस र सलादका लागि उपयुक्त।',status:'available'},
{id:'kalo-bhatmas',sku:'SAANJH-KALO-BHATMAS-1KG',sortOrder:100,featured:false,slug:'kalo-bhatmas',nameEnglish:'Kalo Bhatmas',nameNepali:'कालो भटमास',category:'beans',packSizes:['1 kg'],accentColor:'#3f4143',accentSoft:'#dedede',descriptionEnglish:'Black soybeans for traditional snacks and household cooking.',descriptionNepali:'परम्परागत खाजा र घरायसी खानाका लागि कालो भटमास।',storageEnglish:dryEn,storageNepali:dryNe,useEnglish:'Use in roasted snacks, curries and traditional preparations.',useNepali:'भुटेको खाजा, तरकारी र परम्परागत परिकारमा प्रयोग गर्नुहोस्।',status:'available'}]
export const getProduct=(slug:string)=>products.find(p=>p.slug===slug)
